package org.example.enums;

public enum TaskStage {
    CREATED,
    PLANNING_QUERIES,
    SEARCHING_OPENALEX,
    SEARCHING_ARXIV,
    DEDUPLICATING,
    RANKING,
    FETCHING_FULL_TEXT,
    PARSING_FULL_TEXT,
    INDEXING,
    ANALYZING_PAPERS,
    GENERATING_REPORT,
    COMPLETED,
    FAILED,
    INTERRUPTED
}
